catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1
allowBuilds:
  esbuild: true
overrides:
  vite@*: "catalog:"
  vitest: 4.1.11
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
